// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chris.proto;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chris.proto.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
