// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.chris.proto;

public final class StudentProto {
  private StudentProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chris_proto_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chris_proto_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chris_proto_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chris_proto_MyResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chris_proto_StudentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chris_proto_StudentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chris_proto_StudentResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chris_proto_StudentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rStudent.proto\022\017com.chris.proto\"\031\n\tMyRe" +
      "quest\022\014\n\004name\030\001 \001(\t\"\037\n\nMyResponse\022\021\n\trea" +
      "l_name\030\002 \001(\t\"\035\n\016StudentRequest\022\013\n\003age\030\001 " +
      "\001(\005\":\n\017StudentResponse\022\014\n\004name\030\001 \001(\t\022\013\n\003" +
      "age\030\002 \001(\005\022\014\n\004city\030\003 \001(\t2\273\001\n\016StudentServi" +
      "ce\022N\n\021GetRealNameByName\022\032.com.chris.prot" +
      "o.MyRequest\032\033.com.chris.proto.MyResponse" +
      "\"\000\022Y\n\020GetStudentsByAge\022\037.com.chris.proto" +
      ".StudentRequest\032 .com.chris.proto.Studen" +
      "tResponse\"\0000\001B!\n\017com.chris.protoB\014Studen" +
      "tProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_chris_proto_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chris_proto_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chris_proto_MyRequest_descriptor,
        new String[] { "Name", });
    internal_static_com_chris_proto_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_chris_proto_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chris_proto_MyResponse_descriptor,
        new String[] { "RealName", });
    internal_static_com_chris_proto_StudentRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_chris_proto_StudentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chris_proto_StudentRequest_descriptor,
        new String[] { "Age", });
    internal_static_com_chris_proto_StudentResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_chris_proto_StudentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chris_proto_StudentResponse_descriptor,
        new String[] { "Name", "Age", "City", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
